import pytest
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, FloatType, TimestampType

@pytest.fixture(scope="session")
def spark():
    """Initialize a local Spark session for testing pipeline outputs."""
    return SparkSession.builder \
        .appName("DABPipelineRegressionTest") \
        .master("local[*]") \
        .getOrCreate()

def test_patient_summary_table_schema_regression(spark):
    """
    REGRESSION TEST: Ensures that updates to DAB configurations or pipeline scripts 
    do not alter or break the schema contract of the gold patient summary table.
    """
    
    # 1. Define the Expected Gold Standard Schema Contract (The Contract that MUST NOT regress)
    expected_schema = StructType([
        StructField("patient_id", StringType(), nullable=False),
        StructField("encounter_count", IntegerType(), nullable=True),
        StructField("total_cost", FloatType(), nullable=True),
        StructField("last_visit_date", TimestampType(), nullable=True)
    ])

    # 2. Simulate reading the output table generated by the Databricks pipeline deployment
    # (In a real test, this reads the Delta table path or catalog table produced by the DAB job)
    simulated_pipeline_output_df = spark.createDataFrame(
        [("P1001", 3, 1250.50, None)], 
        schema=expected_schema
    )

    # 3. Assertions (Catching Regressions)
    actual_schema = simulated_pipeline_output_df.schema

    # Check 1: Verify column names and count
    expected_fields = {field.name: field.dataType for field in expected_schema.fields}
    actual_fields = {field.name: field.dataType for field in actual_schema.fields}

    assert actual_fields == expected_fields, (
        f"\n[REGRESSION DETECTED!] Schema mismatch in patient summary table!\n"
        f"Expected Schema: {expected_fields}\n"
        f"Actual Schema:   {actual_fields}\n"
        f"Action: Check recent DAB YAML updates or transformation script changes."
    )

def test_pipeline_row_count_and_nullability_regression(spark):
    """
    REGRESSION TEST: Ensures critical primary keys (patient_id) never become nullable 
    or allow null values after pipeline refactoring.
    """
    expected_schema = StructType([
        StructField("patient_id", StringType(), nullable=False),
        StructField("total_cost", FloatType(), nullable=True)
    ])
    
    df = spark.createDataFrame([("P1001", 500.0)], schema=expected_schema)

    # Check that 'patient_id' is strictly defined as non-nullable (nullable=False)
    patient_id_field = [f for f in df.schema.fields if f.name == "patient_id"][0]
    
    assert patient_id_field.nullable is False, (
        "[REGRESSION DETECTED!] 'patient_id' nullability constraint was violated. "
        "A recent pipeline change allowed nulls in the primary key column."
    )